repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
        files: ^backend/
      - id: ruff-format
        files: ^backend/
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: npx eslint --max-warnings=0
        language: system
        files: \.(ts|tsx|mjs)$
      - id: prettier
        name: prettier
        entry: npx prettier --check
        language: system
        files: \.(ts|tsx|css|json|md|yml)$
