import { cn } from "@/lib/utils/cn";
import { StatusBadge } from "@/components/ui/status-badge";
import type { Status } from "@/types/status";
import { CopyButton } from "./copy-button";
import { highlight, type CodeLang } from "./highlight";

const LANG_LABEL: Record<CodeLang, string> = {
  python: "Python",
  bash: "Shell",
  json: "JSON",
  typescript: "TypeScript",
  text: "Text",
};

export interface CodeBlockProps {
  code: string;
  lang?: CodeLang;
  filename?: string;
  /** Marks examples of APIs that do not exist yet. */
  status?: Status;
  statusLabel?: string;
  lineNumbers?: boolean;
  className?: string;
}

export async function CodeBlock({
  code,
  lang = "python",
  filename,
  status,
  statusLabel,
  lineNumbers = false,
  className,
}: CodeBlockProps) {
  const source = code.replace(/^\n+|\s+$/g, "");
  const html = await highlight(source, lang);
  return (
    <figure
      className={cn(
        "not-prose my-6 overflow-hidden rounded-lg border border-border bg-surface",
        className,
      )}
    >
      <figcaption className="flex items-center justify-between gap-3 border-b border-border-subtle bg-surface-muted/60 px-3 py-1.5 text-xs">
        <span className="flex min-w-0 items-center gap-2">
          <span className="font-medium text-muted-foreground">{LANG_LABEL[lang]}</span>
          {filename ? <span className="truncate font-mono text-foreground">{filename}</span> : null}
          {status ? <StatusBadge status={status} label={statusLabel} /> : null}
        </span>
        <CopyButton text={source} />
      </figcaption>
      <div
        className={cn(
          "overflow-hidden px-4 py-3.5 font-mono text-[13px] leading-6",
          lineNumbers && "code-lines",
        )}
        // Safe: generated by Shiki from repository-authored source; Shiki HTML-escapes the code text.
        dangerouslySetInnerHTML={{ __html: html }}
      />
    </figure>
  );
}
