/** Category constants with no runtime dependencies (safe for client bundles). */
export const METRIC_CATEGORIES = [
  "classification",
  "regression",
  "clinical",
  "calibration",
  "confidence",
  "statistics",
  "effect-size",
  "multiple-testing",
  "segmentation",
  "detection",
  "text-generation",
  "semantic",
  "factuality",
  "llm-judge",
  "reasoning",
  "rag",
  "structured-output",
  "safety",
  "robustness",
  "uncertainty",
  "agents",
  "multilingual",
  "code",
  "long-context",
  "efficiency",
] as const;

export type MetricCategory = (typeof METRIC_CATEGORIES)[number];

export const CATEGORY_LABEL: Record<MetricCategory, string> = {
  classification: "Classification",
  regression: "Regression",
  clinical: "Clinical",
  calibration: "Calibration",
  confidence: "Confidence intervals",
  statistics: "Statistical tests",
  "effect-size": "Effect sizes",
  "multiple-testing": "Multiple testing",
  segmentation: "Segmentation",
  detection: "Object detection",
  "text-generation": "Text generation",
  semantic: "Semantic similarity",
  factuality: "Factuality and QA",
  "llm-judge": "LLM-as-a-judge",
  reasoning: "Reasoning",
  rag: "Retrieval and RAG",
  "structured-output": "Structured output and tools",
  safety: "Safety and responsible AI",
  robustness: "Robustness and reliability",
  uncertainty: "Calibration and uncertainty",
  agents: "Agents and tool use",
  multilingual: "Multilingual",
  code: "Code generation",
  "long-context": "Long context and summarization",
  efficiency: "Inference efficiency and cost",
};
